# -*- coding: utf-8 -*-
"""task3analyze.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1suFEXgKvF42V2WoID4P8N-tJFCqi3IZN
"""

import sqlite3
import numpy as np
import matplotlib.pyplot as plt

conn = sqlite3.connect('shiptivity.db')

c = conn.cursor()

c.execute("SELECT * from user")

user_list = c.fetchall()

conn.commit()

c.execute("SELECT * from login_history")

login_history_list = c.fetchall()

conn.commit()

c.execute("SELECT * from card")

card_list = c.fetchall()

conn.commit()

c.execute("SELECT * from card_change_history")

card_change_history_list = c.fetchall()

conn.commit()


conn.close()

user_arr = np.array(user_list)
login_history_arr = np.array(login_history_list)
card_arr = np.array(card_list)
card_change_history_arr = np.array(card_change_history_list)

unix_time_arr = login_history_arr[:, 2]
print(unix_time_arr)
print(np.min(unix_time_arr))

plt.hist(unix_time_arr, bins=363)
plt.xlabel('Date in Unix')
plt.ylabel('# of users logged in')
plt.title('Daily # of User')
plt.show()

card_change_history_unix_arr = card_change_history_arr[:, 6]
plt.hist(card_change_history_unix_arr, bins=363)
plt.xlabel('Date in Unix')
plt.ylabel('# of status change per card')
plt.title('number of status changes by card')
plt.show()